"""Check dependencies and optionally run and validate a fresh small simulation."""
import argparse
import importlib.metadata
import json
from pathlib import Path
import subprocess
import sys
import tempfile

REPO = Path(__file__).resolve().parent


def validate_channel(path, expected_steps):
    import numpy as np

    # Only called on the output just generated by this process.
    with np.load(path, allow_pickle=True) as data:
        if not np.array_equal(data['valid_steps'], np.arange(expected_steps)):
            raise ValueError('Some satellite positions have no valid channel')
        if len(data['H_by_step']) != expected_steps or len(data['tau_by_step']) != expected_steps:
            raise ValueError('Channel count does not match the configuration')
        for h, tau in zip(data['H_by_step'], data['tau_by_step']):
            h, tau = np.asarray(h), np.asarray(tau)
            if h.ndim != 4 or tau.ndim != 2 or h.shape[-2:] != tau.shape:
                raise ValueError('Unexpected channel/delay dimensions')
            if not np.all(np.isfinite(h)) or not np.all(np.isfinite(tau)):
                raise ValueError('Non-finite channel coefficients or delays')
            if np.any(tau < 0) or not np.any(np.abs(h) > 0):
                raise ValueError('Negative delay or empty channel')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--run-example', action='store_true',
                        help='Run the three-position example and generate plots')
    args = parser.parse_args()
    problems = []
    if sys.version_info[:2] != (3, 12):
        problems.append('Use Python 3.12 for the recorded environment')
    for line in (REPO / 'requirements.txt').read_text().splitlines():
        if not line.strip() or line.startswith('#'):
            continue
        name, expected = line.split('==')
        try:
            actual = importlib.metadata.version(name)
        except importlib.metadata.PackageNotFoundError:
            actual = 'missing'
        if actual != expected:
            problems.append(f'{name}: expected {expected}, found {actual}')
    if problems:
        print('\n'.join(problems), file=sys.stderr)
        return 1
    subprocess.run([sys.executable, '-m', 'pip', 'check'], check=True)
    from Hybrid_channel.trajectory import set_mitsuba_variant
    print('Mitsuba backend:', set_mitsuba_variant(), flush=True)
    print('Environment check passed; this alone does not validate RT execution.', flush=True)
    if not args.run_example:
        return 0
    result_root = REPO / 'Result'
    result_root.mkdir(exist_ok=True)
    run_root = Path(tempfile.mkdtemp(prefix='installation_check_', dir=result_root))
    subprocess.run([sys.executable, str(REPO / 'run_simulation.py'),
                    '--config', str(REPO / 'Config/example.json'),
                    '--output-root', str(run_root)], cwd=REPO, check=True)
    runs = list(run_root.glob('example_*'))
    if len(runs) != 1:
        raise ValueError(f'Expected one new run under {run_root}')
    run = runs[0]
    config = json.loads((REPO / 'Config/example.json').read_text())
    validate_channel(run / 'channel.npz', config['cli']['num-steps'])
    subprocess.run([sys.executable, str(REPO / 'plot_results.py'), str(run),
                    '--trusted-local-output'], cwd=REPO, check=True)
    for name in ('metrics.csv', 'pdp_cfr.png', 'cfr.npz'):
        if not (run / 'analysis' / name).is_file():
            raise ValueError(f'Missing analysis output: {name}')
    print(f'Example check passed: {run}')
    print('This checks execution and output validity, not reference-model agreement.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
