# Source: YuChein/consistent_random_clusters.py; SHA-256 in docs/provenance.json.
# Modified for this local review on 2026-09-23: packaging and documentation.
# Original code rights: research team (confirmed by project owner); LICENSE pending.
# B17: freeze RC state at t0 and evaluate fixed scatterers. Positions: m; time: s. Output is RC-only with absolute delays; deterministic RT tracking is not implemented.

"""
Temporal/spatial consistency extension for the stochastic random-cluster part
of the map-based hybrid NTN channel.

This module is intentionally scoped to the random clusters generated by the
Clause 8 hybrid model. Deterministic RT path tracking and soft birth/death
fading are handled elsewhere.
"""

from __future__ import annotations

import copy
import warnings

import numpy as np

from .hybrid_channel import (
    anchor_rc_power,
    compute_channel_coefficients,
    compute_virtual_powers,
    expand_clusters_to_rays,
    generate_hybrid_pdp,
    generate_initial_phases,
    generate_xpr,
    normalize_virtual_powers,
)

C0 = 299_792_458.0


class _NoRng:
    def __getattr__(self, name):
        raise RuntimeError(
            f"RNG use is forbidden during per-step RC evaluation: {name}"
        )


def wrap_pi(x):
    return (x + np.pi) % (2.0 * np.pi) - np.pi


def wrap_zenith(theta):
    theta = np.mod(theta, 2.0 * np.pi)
    if np.isscalar(theta):
        return 2.0 * np.pi - theta if theta > np.pi else theta
    theta = np.asarray(theta)
    out = theta.copy()
    mask = out > np.pi
    out[mask] = 2.0 * np.pi - out[mask]
    return out


def angles_to_unit(phi, theta):
    """3GPP spherical angles -> Cartesian unit vector."""
    return np.array([
        np.sin(theta) * np.cos(phi),
        np.sin(theta) * np.sin(phi),
        np.cos(theta),
    ], dtype=np.float64)


def unit_to_angles(u):
    """Cartesian unit vector -> (azimuth phi, zenith theta)."""
    u = np.asarray(u, dtype=np.float64)
    n = np.linalg.norm(u)
    if n == 0.0:
        raise ValueError("zero-length direction vector")
    v = u / n
    phi = float(np.arctan2(v[1], v[0]))
    theta = float(np.arccos(np.clip(v[2], -1.0, 1.0)))
    return phi, theta


def _rt_arrays(rt_paths):
    if not rt_paths:
        return np.array([]), np.array([])
    tau = np.array([p["tau_rt"] for p in rt_paths], dtype=np.float64)
    power = np.array([p["power_rt"] for p in rt_paths], dtype=np.float64)
    return tau, power


def _make_object_copy(x):
    return copy.deepcopy(x)


def freeze_random_cluster_state(
    rt_paths_t0,
    scenario_name,
    p_ut,
    p_sat0,
    fc_GHz,
    elev_deg=None,
    rng=None,
    seed=None,
    config=None,
    eps_los_aligned=1e-4,
):
    """
    Freeze all stochastic random-cluster identity at t0.

    RNG is used only inside this function. The returned state is consumed by
    evaluate_random_clusters(), which is deterministic and does not accept RNG.
    """
    if rng is None:
        rng = np.random.default_rng(seed)
    if config is None:
        config = {}

    p_ut = np.asarray(p_ut, dtype=np.float64)
    p_sat0 = np.asarray(p_sat0, dtype=np.float64)
    a0 = p_sat0 - p_ut
    slant0 = float(np.linalg.norm(a0))
    if slant0 <= 0.0:
        raise ValueError("p_sat0 and p_ut must not coincide")
    d_los0 = a0 / slant0

    hybrid_config = {
        "p0": config.get("p0", 0.2),
        "power_threshold_dB": config.get("power_threshold_dB", -25.0),
        "pdp_bin_size": config.get("pdp_bin_size", 1e-9),
    }
    ray_config = {
        "M": config.get("M", 3),
        "is_LOS_first_cluster": config.get("is_LOS_first_cluster", True),
        "pdp_bin_size": config.get("pdp_bin_size", 1e-9),
    }

    hybrid = generate_hybrid_pdp(
        rt_paths_t0,
        config=hybrid_config,
        rng=rng,
        scenario_name=scenario_name,
        fc_GHz=fc_GHz,
        elev_deg=elev_deg,
    )
    clusters = sorted(hybrid["clusters"], key=lambda c: c["delay"])
    sp = _make_object_copy(hybrid["scenario_params"])
    sp["fc_GHz"] = fc_GHz

    ray_result = expand_clusters_to_rays(clusters, sp, ray_config, rng=rng)
    rays = generate_xpr(ray_result["rays"], sp, rng)
    rays = generate_initial_phases(rays, sp, rng, tx_rx_distance_3D=slant0)

    rays_by_cluster = {}
    for ray in rays:
        rays_by_cluster.setdefault(ray["cluster_id"], []).append(ray)

    frozen_clusters = []
    dropped_los_aligned = 0
    dropped_nonpositive_delay = 0

    for cluster_idx, cluster in enumerate(clusters):
        if cluster.get("source") != "RC":
            continue

        tau_excess0 = float(cluster["delay"])
        if tau_excess0 <= 0.0:
            dropped_nonpositive_delay += 1
            continue

        u_aoa = angles_to_unit(float(cluster["aoa"]), float(cluster["zoa"]))
        cos_psi0 = float(np.dot(u_aoa, d_los0))
        denom = 1.0 - cos_psi0
        if denom < eps_los_aligned:
            dropped_los_aligned += 1
            continue

        D0 = slant0 + C0 * tau_excess0
        exact_denom = 2.0 * (D0 - slant0 * cos_psi0)
        if exact_denom <= 0.0:
            dropped_los_aligned += 1
            continue
        R_s = (D0**2 - slant0**2) / exact_denom
        scatterer_position = p_ut + R_s * u_aoa
        frozen_rays = []
        for ray in rays_by_cluster.get(cluster_idx, []):
            if ray.get("source") != "RC":
                continue
            frozen_rays.append({
                "ray_id": int(ray["ray_id"]),
                "sub_delay": float(ray["delay"] - cluster["delay"]),
                "power_fraction": float(ray["power"] / cluster["power"]) if cluster["power"] > 0 else 0.0,
                "aoa_offset": float(wrap_pi(ray["aoa"] - cluster["aoa"])),
                "aod_offset": float(wrap_pi(ray["aod"] - cluster["aod"])),
                "zoa_offset": float(ray["zoa"] - cluster["zoa"]),
                "zod_offset": float(ray["zod"] - cluster["zod"]),
                "xpr": float(ray.get("xpr", 1.0)),
                "phase": _make_object_copy(ray.get("phase", {})),
                "coupling_permutation": int(ray["ray_id"]),
            })

        frozen_clusters.append({
            "frozen_cluster_id": len(frozen_clusters),
            "source_cluster_id": int(cluster_idx),
            "u_aoa": u_aoa,
            "R_s": float(R_s),
            "scatterer_position": scatterer_position,
            "tau_excess0": tau_excess0,
            "slant0": slant0,
            "aoa": float(cluster["aoa"]),
            "zoa": float(cluster["zoa"]),
            "aod0": float(cluster["aod"]),
            "zod0": float(cluster["zod"]),
            "shadowing_db": float(cluster.get("shadowing_db", 0.0)),
            "initial_power": float(cluster["power"]),
            "rays": frozen_rays,
        })

    state = {
        "type": "consistent_random_cluster_state",
        "scenario_name": scenario_name,
        "scenario_params": sp,
        "config": {"hybrid": hybrid_config, "ray": ray_config},
        "p_ut": p_ut,
        "p_sat0": p_sat0,
        "slant0": slant0,
        "d_los0": d_los0,
        "fc_GHz": float(fc_GHz),
        "fc_Hz": float(fc_GHz * 1e9),
        "wavelength": C0 / (fc_GHz * 1e9),
        "clusters": frozen_clusters,
        "metadata": {
            "num_frozen_rc_clusters": len(frozen_clusters),
            "dropped_los_aligned": dropped_los_aligned,
            "dropped_nonpositive_delay": dropped_nonpositive_delay,
            "eps_los_aligned": eps_los_aligned,
            "rng_scope": "t0 freeze only; per-step evaluation is deterministic",
            "out_of_scope_hooks": [
                "deterministic path-ID birth/death fading",
                "UT mobility",
                "multi-UT spatial correlation random fields",
                "multi-bounce random clusters",
            ],
        },
        "t0_hybrid": hybrid,
    }
    if dropped_los_aligned or dropped_nonpositive_delay:
        warnings.warn(
            "Dropped random clusters during t0 anchoring: "
            f"los_aligned={dropped_los_aligned}, "
            f"nonpositive_delay={dropped_nonpositive_delay}"
        )
    return state


def evaluate_random_clusters(
    state,
    p_sat,
    rt_paths_current=None,
    rx_array_geom=None,
    tx_array_geom=None,
    p_ut=None,
    t=0.0,
    power_threshold_dB=None,
):
    """
    Deterministically evaluate frozen random clusters at one time instant.

    No RNG is used here. All time evolution comes from p_sat and the frozen
    state created by freeze_random_cluster_state().
    """
    p_sat = np.asarray(p_sat, dtype=np.float64)
    p_ut = np.asarray(state["p_ut"] if p_ut is None else p_ut, dtype=np.float64)
    sp = state["scenario_params"]
    fc_Hz = state["fc_Hz"]

    a = p_sat - p_ut
    slant = float(np.linalg.norm(a))
    if slant <= 0.0:
        raise ValueError("p_sat and p_ut must not coincide")
    d_los = a / slant

    tx_to_ut = -d_los
    aod_center, zod_center = unit_to_angles(tx_to_ut)

    rt_tau_abs, rt_power = _rt_arrays(rt_paths_current or [])
    if rt_tau_abs.size:
        first_arrival = float(np.min(rt_tau_abs))
        tau_rt_norm = rt_tau_abs - first_arrival
    else:
        first_arrival = slant / C0
        tau_rt_norm = np.array([], dtype=np.float64)

    tau_abs_all = []
    tau_excess = []
    tau_far_field = []
    z_rc = []
    active_clusters = []
    for frozen in state["clusters"]:
        scatterer = np.asarray(frozen["scatterer_position"], dtype=np.float64)
        R_s = float(frozen["R_s"])
        sat_to_scatterer = float(np.linalg.norm(p_sat - scatterer))
        tau_abs = (sat_to_scatterer + R_s) / C0
        tau_ex = tau_abs - slant / C0
        tau_ex = max(float(tau_ex), 0.0)
        cos_psi = float(np.dot(frozen["u_aoa"], d_los))
        tau_ff_abs = slant / C0 + R_s * (1.0 - cos_psi) / C0
        tau_abs_all.append(float(tau_abs))
        tau_excess.append(tau_ex)
        tau_far_field.append(float(tau_ff_abs))
        z_rc.append(float(frozen["shadowing_db"]))
        active_clusters.append(frozen)

    tau_abs_all = np.asarray(tau_abs_all, dtype=np.float64)
    tau_excess = np.asarray(tau_excess, dtype=np.float64)
    tau_far_field = np.asarray(tau_far_field, dtype=np.float64)
    z_rc = np.asarray(z_rc, dtype=np.float64)

    if len(active_clusters):
        V_RC, V_RT = compute_virtual_powers(
            tau_excess,
            tau_rt_norm,
            sp,
            rng=_NoRng(),
            Z_RC=z_rc,
            Z_RT=np.zeros_like(tau_rt_norm),
        )
        P_RC_virtual, P_RT_virtual = normalize_virtual_powers(V_RC, V_RT, sp)
        P_RC_real = anchor_rc_power(P_RC_virtual, P_RT_virtual, rt_power)
    else:
        P_RC_real = np.array([], dtype=np.float64)

    if power_threshold_dB is None:
        power_threshold_dB = state["config"]["hybrid"].get("power_threshold_dB", -25.0)
    p_max_candidates = []
    if rt_power.size:
        p_max_candidates.append(float(np.max(rt_power)))
    if P_RC_real.size:
        p_max_candidates.append(float(np.max(P_RC_real)))
    threshold = 0.0
    if p_max_candidates:
        threshold = max(p_max_candidates) * 10.0 ** (power_threshold_dB / 10.0)

    clusters = []
    rays = []
    removed_by_power_threshold = 0
    for i, frozen in enumerate(active_clusters):
        power = float(P_RC_real[i])
        if power < threshold:
            removed_by_power_threshold += 1
            continue
        tau_abs = float(tau_abs_all[i])
        cluster_id = int(frozen["frozen_cluster_id"])
        cluster = {
            "delay": tau_abs,
            "tau_excess": float(tau_excess[i]),
            "power": power,
            "source": "RC",
            "cluster_id": cluster_id,
            "aoa": float(frozen["aoa"]),
            "zoa": float(frozen["zoa"]),
            "aod": aod_center,
            "zod": zod_center,
            "shadowing_db": float(frozen["shadowing_db"]),
            "R_s": float(frozen["R_s"]),
            "scatterer_position": np.asarray(frozen["scatterer_position"], dtype=np.float64),
            "far_field_delay": float(tau_far_field[i]),
            "exact_minus_far_field_delay": float(tau_abs - tau_far_field[i]),
        }
        clusters.append(cluster)

        for frozen_ray in frozen["rays"]:
            ray_delay = tau_abs + float(frozen_ray["sub_delay"])
            phase_frozen = _make_object_copy(frozen_ray["phase"])
            carrier_phase = -2.0 * np.pi * fc_Hz * ray_delay
            theta_theta = float(phase_frozen.get("theta_theta", 0.0) + carrier_phase)
            phase = {
                "theta_theta": theta_theta,
                "theta_phi": float(phase_frozen.get("theta_phi", 0.0) + carrier_phase),
                "phi_theta": float(phase_frozen.get("phi_theta", 0.0) + carrier_phase),
                "phi_phi": float(phase_frozen.get("phi_phi", 0.0) + carrier_phase),
            }
            ray = {
                "delay": ray_delay,
                "tau_excess": float(tau_excess[i] + frozen_ray["sub_delay"]),
                "power": power * float(frozen_ray["power_fraction"]),
                "source": "RC",
                "cluster_id": cluster_id,
                "ray_id": int(frozen_ray["ray_id"]),
                "is_los_ray": False,
                "aoa": float(wrap_pi(frozen["aoa"] + frozen_ray["aoa_offset"])),
                "zoa": float(wrap_zenith(frozen["zoa"] + frozen_ray["zoa_offset"])),
                "aod": float(wrap_pi(aod_center + frozen_ray["aod_offset"])),
                "zod": float(wrap_zenith(zod_center + frozen_ray["zod_offset"])),
                "xpr": float(frozen_ray["xpr"]),
                "phase": phase,
                "coupling_permutation": int(frozen_ray["coupling_permutation"]),
            }
            rays.append(ray)

    result = {
        "clusters": clusters,
        "rays": rays,
        "metadata": {
            "slant_m": slant,
            "first_arrival_delay_s": first_arrival,
            "num_rc_clusters": len(clusters),
            "num_rc_rays": len(rays),
            "power_threshold_dB": power_threshold_dB,
            "threshold_power": threshold,
            "num_power_threshold_removed": removed_by_power_threshold,
        },
    }

    if removed_by_power_threshold:
        warnings.warn(
            f"Random-cluster power threshold removed {removed_by_power_threshold} "
            f"of {len(active_clusters)} frozen clusters at {power_threshold_dB} dB"
        )

    if rx_array_geom is not None and tx_array_geom is not None:
        channel = compute_channel_coefficients(
            rays,
            rx_array_geom,
            tx_array_geom,
            state["fc_GHz"],
            velocity_vec=None,
            t=0.0,
        ) if rays else _empty_channel(rx_array_geom, tx_array_geom, state["fc_GHz"])
        result["channel"] = channel
    return result


def _empty_channel(rx_array_geom, tx_array_geom, fc_GHz):
    U = np.asarray(rx_array_geom).shape[0]
    S = np.asarray(tx_array_geom).shape[0]
    return {
        "H": np.zeros((U, S, 0, 0), dtype=np.complex64),
        "tau": np.zeros((0, 0), dtype=np.float64),
        "fc_GHz": fc_GHz,
        "wavelength": 0.3 / fc_GHz,
        "t": 0.0,
        "metadata": {
            "num_rx_ant": U,
            "num_tx_ant": S,
            "num_clusters": 0,
            "M_max": 0,
            "total_rays": 0,
        },
    }


def random_cluster_doppler_from_delay(times_s, delays_s, fc_GHz):
    """Finite-difference Doppler estimate f_D = -f_c d tau/dt."""
    times_s = np.asarray(times_s, dtype=np.float64)
    delays_s = np.asarray(delays_s, dtype=np.float64)
    d_tau_dt = np.gradient(delays_s, times_s)
    return -(fc_GHz * 1e9) * d_tau_dt
